### ISSUE TITLE
Managers can't set other user's phone number

### ISSUE THREAD

**Issue by frisi** [collective/collective.smsauthenticator#11]
seems that site-admins can't set the phone number of existing users.

is this a use-case that is supposed to work?:

* login as site-admin
* activate sms auth globally in @@sms-authenticator-settings
  and activate it for all existing users (@@sms-authenticator-enable-for-all-users)
*  visit https://myhost.com/@@usergroup-userprefs
* create user account (eg. tester)
* edit personal prefs of tester (@@user-information?userid=tester) 
* supply mobile number (leave other fields with defaults - see screenshot)

![smsauth](https://cloud.githubusercontent.com/assets/1120517/14983161/cd148758-113b-11e6-9d64-6a9f2c472b3f.png)
* submit the form

what i get is a status message that tells me that the personal preferences have successfully been saved.
but the field for the mobile number is still empty.

**Comment by barseghyanartur** [comment]
@frisi:

Wny do you need this? If globally enabled and not yet set, users are obliged to set up their numbers themselves. The process is [well thought](https://pypi.python.org/pypi/collective.smsauthenticator#case-1-enabling-the-two-step-verification). I can't imagine a case, when admins would need to set up numbers for users. I haven't seen that anywhere as well. Not in Gmail, not in LinkedIn or any other site.

**Comment by frisi** [comment]
thanks for your quick reply @barseghyanartur 

in our case smsauthenticator will be used in an intranet with about 20 user accounts.
all users are employees and we know a working email-address and phone-number for each of them.
currently there is no 2-factor auth in place.

it perfectly makes sense to let them set and validate their mobile number when logging in (as gmail or other portals do that - if the users decided to use 2-factor auth)

the difference to the gmail use-case is:
* we know their phone numbers and
* we want to force users to use 2-factor auth

plone also lets you add a user and set a password without validating the email. so it felt naturally to ask if it is possible to set the mobile number as a site-admin, too.

if this is not supported we need to tell all users that sms-authentication will be activated on may 15th  and also add some information how to set and validate their phone numbers.


if this makes sense to you now we can keep this issue open and remove the "wontfix" label. maybe we or somebody else needs it for another project and is willing to implement this.

if you don't want collective.smsauthenticator to support this use-case please provide a strong/good argument against it.

**Comment by barseghyanartur** [comment]
@frisi:

Currently, you can [force](http://pythonhosted.org/collective.smsauthenticator/#main) users to use the two-factor auth.

Unfortunately, there is not "does not make sense" label. :)

- My arguments - the desired functionality is not needed. KISS principle.
- Package itself does provide screen shots and [documentation](http://pythonhosted.org/collective.smsauthenticator/#main) on the whole setup/recover process. Make use of it.

**Comment by frisi** [comment]
* ad KISS: we can also add a PLIP for plone to remove the possibility to set a password for a user directly in the `@@new-user` form. 
* ad docs: i know there is documentation, and i already make use of it.
  however i need to translate it as not all users speak english. and i still need to inform them (=extra work)

so for you this usecase does not make sense.
what i'm not sure about is whether you are completely against it or not.

@barseghyanartur would you merge a pull request that lets site-admins change mobile numbers for existing users?

**Comment by barseghyanartur** [comment]
@puittenbroek:

Thoughts? :)

**Comment by puittenbroek** [comment]
I would enable to ability to change the fields by admins, our client also had this problem ;)

**Comment by barseghyanartur** [comment]
@frisi:

Your efforts would be greatly appreciated.

**Comment by pcdummy** [comment]
Works for us with current master.

**Comment by frisi** [comment]
thanks for your work @puittenbroek and for giving in @barseghyanartur ;-)
