### ISSUE TITLE
Make smsauthenticator work with overlays

### ISSUE THREAD

**Issue by frisi** [collective/collective.smsauthenticator#12]
currently you'll need to deactivate popupforms.js (or at least overlays for the login process) on plone 4.x to make sure users see the status messages.

otherwhise users will
* click on login
* type username and password in the overlay and press login
* overlay will close
* the user will be redirected to the page the clicked on the "login" action without beeing logged in

instead of this we should show the @@sms-authenticator-token in the status page, or at least rediret the user there

we had similar problem with collective.pwexpiry. maybe this helps fix this https://github.com/collective/collective.pwexpiry/pull/10

in the meantime the readme should contain a warning that popupforms.js should be disabled when using collective.smsauthenticator.

**Comment by barseghyanartur** [comment]
@frisi:

Correct. Some work towards that has been already done in [fixes](https://github.com/collective/collective.smsauthenticator/commits/fixes) branch. To be merged to master some day.

**Comment by puittenbroek** [comment]
Hi @frisi, can you check if this is also the case with the current master?

**Comment by pcdummy** [comment]
@puittenbroek do you mean the fixes branch? Gonna test this now.

**Comment by barseghyanartur** [comment]
@pcdummy:

Check the commits to the current master.

**Comment by pcdummy** [comment]
Thanks for your fast response, i can't see commits for popuforms.js in master? Can you point me to the commit?

**Comment by pcdummy** [comment]
We just tried the current master with popups on Plone 4.3.9 and it works. Sadly not with our fix for pwexpiry @frisi  mentioned above.

**Comment by puittenbroek** [comment]
That fix for pwexpiry would need to include the filters we use to keep the overlay open?

**Comment by frisi** [comment]
thanks @puittenbroek  and @barseghyanartur 

as neither pwexpiry should include fixes/logic for smsauth nor the other way round, we'll add a patched version of popupforms.js to our policy package.
